---
# tasks file for w10

- name: Add users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    create_home: yes
    generate_ssh_key: yes
    password: "{{ 'my_password' | password_hash('sha512') }}"
    skeleton: /etc/skel
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop: "{{ user_list }}"
  become: yes

- name: Install Packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: present
    autoclean: yes
    autoremove: yes
    install_recommends: yes
    update_cache: yes
  loop: "{{ package_list }}"
  become: yes

- name: Start Services
  service:
    name: "{{ item.name }}"
    state: started
  loop: "{{ service_list }}"
  become: yes