---
# tasks file for w10

- name: Add users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    create_home: yes
    generate_ssh_key: yes
    password: "{{ my_password | password_hash('sha512', 'mysecretpassword') }}"
    skeleton: /etc/skel
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop:
    - "{{ user_list }}"
